### ISSUE TITLE
files in ./post not be deleted in repository when it deleted in Gridea first

### ISSUE THREAD

**Issue by ItsMango** [getgridea/gridea#773]
Hi Sir,

I met something strange, and don't know whether it is a bug.

Firstly, I write something in a blog, and name this blog"SharingIt".
And then, I click the button in Gridea to synchronize this blog into github.
I can see a new folder ./post/sharingit created in my repository, it's alright now.

Next, I try to delete this blog "SharingIt" in Gridea, and synchronize to github.
And now, I can see "SharingIt" deleted in the webpage, it's alright.
But in my repository, this folder ./post/sharingit is still there.

I don't konw if this is normal. or I just mistake something?

Regards
Ed

**Comment by china-365vip** [comment]
Hi，If this problem affects you, please describe it in detail
Good luck！

**Comment by china-365vip** [comment]
Please provide pictures if possible

**Comment by china-365vip** [comment]
Hello, although you deleted the articles on the web page, gridea does not have permission to delete your repository files. This is not caused by configuration errors. If you want to delete them completely, please delete the repository manually on GitHub
If this is not your problem, please describe it in detail, thank you!
Good luck！

**Comment by china-365vip** [comment]
Hello, although you deleted the articles on the web page, gridea does not have permission to delete your repository files. This is not caused by configuration errors. If you want to delete them completely, please delete the repository manually on GitHub
If this is not your problem, please describe it in detail, thank you!
Good luck！

**Comment by ItsMango** [comment]
hi，thanks for your reply，I think your answer is quite clearly，I would delete them manually.
